import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const TEST_EMAIL="joao.guilherme@radiod.com.br";
const DEFAULT_RECIPIENTS=[TEST_EMAIL,"jany.lima@radiod.com.br","Francielly.Garcia@radiod.com.br","Simone.Evangelista@radiod.com.br"];
const RADIOS=["DUMONT FM","METROPOLITANA FM","EDUCADORA FM","MIX RIO FM"];
function esc(s:string){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}
function pct(n:number){return `${n>=0?"+":""}${n.toFixed(1)}%`}
function rowHtml(x:any,mode="growth"){const val=mode==="drop"?`-${x.queda}`:pct(x.cres);return `<tr><td style="padding:9px 5px;border-bottom:1px solid #eee"><b>${esc(x.artista)}</b><br>${esc(x.musica)}</td><td align="center" style="border-bottom:1px solid #eee">${x.ant}</td><td align="center" style="border-bottom:1px solid #eee"><b>${x.ult}</b></td><td align="center" style="border-bottom:1px solid #eee"><b>${val}</b></td></tr>`}
function brDate(d:Date){return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"2-digit",year:"numeric"}).format(d)}
Deno.serve(async(req:Request)=>{try{
 const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
 const [{data:secret},{data:resendKey}]=await Promise.all([supabase.rpc("get_app_secret",{secret_name:"cron_shared_secret"}),supabase.rpc("get_app_secret",{secret_name:"resend_api_key"})]);
 if(!secret||req.headers.get("x-radar-secret")!==secret)return Response.json({error:"unauthorized"},{status:401});if(!resendKey)return Response.json({error:"missing resend api key"},{status:500});
 let recipients=DEFAULT_RECIPIENTS,isTest=false;try{const b=await req.json();if(b?.test===true){recipients=[TEST_EMAIL];isTest=true;}else if(Array.isArray(b?.recipients)){const valid=b.recipients.filter((x:any)=>typeof x==="string"&&x.includes("@"));if(valid.length)recipients=[...new Set(valid)]}}catch{}
 const since=new Date(Date.now()-16*86400000).toISOString();let rows:any[]=[];const page=1000;
 for(let from=0;;from+=page){const {data,error}=await supabase.from("radio_airplay").select("radio,artista,musica,tocou_em,genero").in("radio",RADIOS).gte("tocou_em",since).order("tocou_em",{ascending:true}).range(from,from+page-1);if(error)return Response.json({error:error.message},{status:500});rows.push(...(data??[]));if((data??[]).length<page)break;}
 const mx=rows.reduce((m,r)=>Math.max(m,new Date(r.tocou_em).getTime()),0);if(!mx)return Response.json({error:"no data"},{status:500});const d7=mx-7*86400000,d14=mx-14*86400000;
 const map=new Map<string,any>();for(const r of rows){const t=new Date(r.tocou_em).getTime();if(t<d14||t>mx)continue;const k=`${r.radio}|||${r.artista}|||${r.musica}`;if(!map.has(k))map.set(k,{radio:r.radio,artista:r.artista,musica:r.musica,genero:r.genero||"Não informado",ant:0,ult:0});const x=map.get(k);if(t<d7)x.ant++;else x.ult++;}
 const all=[...map.values()].map(x=>({...x,aumento:x.ult-x.ant,cres:x.ant?((x.ult-x.ant)*100/x.ant):0}));const rises=all.filter(x=>x.ant>0&&x.ult>=3&&x.ult>x.ant);const drops=all.filter(x=>x.ant>=3&&x.ult<x.ant).map(x=>({...x,queda:x.ant-x.ult}));
 const by=new Map<string,any[]>();for(const r of RADIOS)by.set(r,rises.filter(x=>x.radio===r).sort((a,b)=>b.aumento-a.aumento||b.cres-a.cres).slice(0,8));
 const cross=new Map<string,any>();for(const x of rises){const k=`${x.artista}|||${x.musica}`;const z=cross.get(k)||{artista:x.artista,musica:x.musica,radios:[]};if(!z.radios.includes(x.radio))z.radios.push(x.radio);cross.set(k,z)}const both=[...cross.values()].filter(x=>x.radios.length===RADIOS.length).slice(0,8);
 const genreStats=RADIOS.map(r=>{const a=all.filter(x=>x.radio===r&&x.genero&&x.genero!=="Não informado");const g=new Map<string,{ant:number,ult:number}>();for(const x of a){const z=g.get(x.genero)||{ant:0,ult:0};z.ant+=x.ant;z.ult+=x.ult;g.set(x.genero,z)}return {radio:r,items:[...g.entries()].map(([genero,z])=>({...z,genero,cres:z.ant?((z.ult-z.ant)*100/z.ant):0})).filter(x=>x.ult>x.ant&&x.ult>=5).sort((a,b)=>(b.ult-b.ant)-(a.ult-a.ant)).slice(0,3)}});
 const topOverall=[...rises].sort((a,b)=>b.aumento-a.aumento||b.cres-a.cres).slice(0,5);const reportDate=brDate(new Date());
 let html=`<div style="max-width:760px;margin:auto;font-family:Arial,sans-serif;color:#222"><p>Olá, tudo bem? Você está recebendo o <b>“Radar de Músicas em Ascensão”</b> das rádios monitoradas pelo sistema <b>“IA NO RÁDIO”</b>.</p><p><b>${reportDate}</b> — O relatório compara a quantidade de vezes que cada música tocou nos <b>últimos 7 dias</b> com os <b>7 dias anteriores</b>. Assim, conseguimos identificar quais músicas estão ganhando força, perdendo espaço ou crescendo nas rádios monitoradas.</p><p>Para mais detalhes da programação acesse: <a href="https://monitoramento.ianoradio.com/">https://monitoramento.ianoradio.com/</a></p>${isTest?`<div style="background:#fff7ed;padding:12px 16px;border-radius:8px;margin:15px 0"><b>TESTE — enviado somente para ${TEST_EMAIL}</b></div>`:""}`;
 html+=`<h2>PRINCIPAIS MOVIMENTOS — ${RADIOS.join(" + ")}</h2><p style="color:#666">Ranking conjunto das quatro rádios, considerando os maiores aumentos de execuções.</p><table style="width:100%;border-collapse:collapse"><tr><th align="left">Música</th><th>Antes</th><th>7 dias</th><th>Crescimento</th></tr>${topOverall.map(x=>rowHtml(x)).join("")||`<tr><td colspan="4">Nenhum movimento relevante.</td></tr>`}</table>`;
 for(const r of RADIOS){html+=`<h2 style="margin-top:28px">${esc(r)}</h2><table style="width:100%;border-collapse:collapse"><tr><th align="left">Música</th><th>Antes</th><th>7 dias</th><th>Crescimento</th></tr>${(by.get(r)??[]).map(x=>rowHtml(x)).join("")||`<tr><td colspan="4" style="padding:10px;color:#777">Nenhum movimento relevante.</td></tr>`}</table>`}
 if(both.length)html+=`<h2 style="margin-top:28px">CRESCENDO NAS QUATRO RÁDIOS</h2><p style="color:#666">Músicas que apresentaram crescimento simultaneamente em todas as quatro rádios.</p><ul>${both.map(x=>`<li style="margin:7px 0"><b>${esc(x.artista)}</b> — ${esc(x.musica)}</li>`).join("")}</ul>`;
 const dropList=drops.sort((a,b)=>b.queda-a.queda).slice(0,8);html+=`<h2>QUEDAS RELEVANTES — ${RADIOS.join(" + ")}</h2><p style="color:#666">Ranking conjunto das quatro rádios, considerando as maiores reduções de execuções.</p><table style="width:100%;border-collapse:collapse"><tr><th align="left">Música</th><th>Antes</th><th>7 dias</th><th>Variação</th></tr>${dropList.map(x=>rowHtml(x,"drop")).join("")||`<tr><td colspan="4" style="padding:10px;color:#777">Nenhuma queda relevante.</td></tr>`}</table>`;
 html+=`<h2>GÊNEROS EM MOVIMENTO</h2>`;for(const g of genreStats){html+=`<h3>${esc(g.radio)}</h3><ul>${g.items.map(x=>`<li><b>${esc(x.genero)}</b>: ${x.ant} → ${x.ult} (${pct(x.cres)})</li>`).join("")||"<li>Sem tendência consistente identificada.</li>"}</ul>`}
 html+=`<p style="color:#999;font-size:13px;margin-top:30px">Radar ianoradio. O relatório TOP 10 permanece separado e não é alterado por este Radar.</p></div>`;
 const text=`RADAR DIÁRIO — RESUMO DE DADOS - IA NO RÁDIO\n\nOlá, tudo bem? Você está recebendo o “Radar de Músicas em Ascensão” das rádios monitoradas pelo sistema “IA NO RÁDIO”.\n\n${reportDate} — Comparação dos últimos 7 dias com os 7 dias anteriores para identificar crescimento, queda e movimentos nas rádios monitoradas.\n\nPara mais detalhes da programação acesse: https://monitoramento.ianoradio.com/\n\nPRINCIPAIS MOVIMENTOS — ${RADIOS.join(" + ")}\n`+topOverall.map(x=>`${x.artista} - ${x.musica}: ${x.ant} -> ${x.ult} (${pct(x.cres)})`).join("\n");
 const send=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:"Radar ianoradio <relatorios@ianoradio.com>",to:recipients,subject:`${isTest?"[TESTE] ":""}RADAR DIÁRIO — RESUMO DE DADOS - IA NO RÁDIO`,html,text})});if(!send.ok)return Response.json({error:"resend failed",detail:await send.text()},{status:502});return Response.json({ok:true,test:isTest,recipients,radios:RADIOS,rows_loaded:rows.length,rises:rises.length,drops:drops.length,both:both.length});
}catch(e){return Response.json({error:String(e)},{status:500})}});
